#!/usr/bin/env python3
import json
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CORPORA = ROOT.parent / "corpora" / "data"
OUTPUT = ROOT / "src" / "word_lists.rs"

Spec = tuple[str, str | None, str | None]

ADJECTIVE_SOURCES: list[Spec] = [
    ("words/adjs.json", "adjs", None),
]
COLOR_SOURCES: list[Spec] = [
    ("colors/web_colors.json", "colors", "color"),
    ("colors/xkcd.json", "colors", "color"),
]
FOOD_SOURCES: list[Spec] = [
    ("foods/fruits.json", "fruits", None),
    ("foods/vegetables.json", "vegetables", None),
    ("foods/breads_and_pastries.json", "breads", None),
    ("foods/breads_and_pastries.json", "pastries", None),
    ("foods/condiments.json", "condiments", None),
    ("foods/fish.json", "fish", None),
    ("foods/shellfish.json", "fish", None),
    ("foods/herbs_n_spices.json", "herbs", None),
    ("foods/herbs_n_spices.json", "spices", None),
    ("foods/herbs_n_spices.json", "mixtures", None),
    ("foods/pizzaToppings.json", "pizzaToppings", None),
    ("foods/sandwiches.json", "sandwiches", None),
    ("foods/sausages.json", "sausages", None),
    ("foods/poultry.json", "bird", None),
    ("foods/menuItems.json", "menuItems", None),
    ("foods/tea.json", "teas", None),
    ("foods/ham.json", "meat", None),
    ("foods/curds.json", "curds", None),
    ("foods/apple_cultivars.json", "cultivars", None),
]
SCIFI_SOURCES: list[Spec] = [
    ("science/planets.json", "planets", None),
    ("science/minor_planets.json", "minor_planets", None),
    ("science/elements.json", "elements", None),
    ("technology/new_technologies.json", "technologies", None),
    ("technology/programming_languages.json", None, None),
    ("technology/programming_languages_popular.json", "programming_languages_popular", None),
    ("technology/computer_sciences.json", "computer_sciences", None),
]
LAUNCH_FILE = "transportation/launchVehicleList.json"

ALLOW_CHARS = set("abcdefghijklmnopqrstuvwxyz- ")


def normalize(word: str, *, allow_digits: bool = False) -> str | None:
    word = unicodedata.normalize("NFKD", word).encode("ascii", "ignore").decode("ascii")
    word = word.replace("&", " and ")
    word = word.replace("/", " ")
    word = word.replace("+", " ")
    word = word.replace("'", "")
    word = word.replace(".", " ")
    word = word.strip().lower()
    if not word:
        return None
    if not allow_digits and any(ch.isdigit() for ch in word):
        return None
    clean_chars: list[str] = []
    for ch in word:
        if ch in ALLOW_CHARS or (allow_digits and ch.isdigit()):
            clean_chars.append(ch)
    cleaned = "".join(clean_chars)
    cleaned = "-".join(part for part in cleaned.split() if part)
    cleaned = cleaned.strip("-")
    if not cleaned:
        return None
    return cleaned


def load_values(relpath: str, key: str | None):
    data = json.loads((CORPORA / relpath).read_text())
    return data if key is None else data[key]


def collect_words(specs: list[Spec], *, allow_digits=False):
    store: set[str] = set()
    for relpath, key, attr in specs:
        values = load_values(relpath, key)
        for value in values:
            if isinstance(value, str):
                norm = normalize(value, allow_digits=allow_digits)
                if norm:
                    store.add(norm)
            elif isinstance(value, dict) and attr:
                field = value.get(attr)
                if isinstance(field, str):
                    norm = normalize(field, allow_digits=allow_digits)
                    if norm:
                        store.add(norm)
    return store


def collect_launch_vehicles():
    data = json.loads((CORPORA / LAUNCH_FILE).read_text())
    words: set[str] = set()
    for company in data.get("aerospaceCompany", []):
        for rocket in company.get("rockets", []):
            name = rocket.get("vehicle")
            norm = normalize(name)
            if norm:
                words.add(norm)
    return words


def write_array(name: str, words: list[str]):
    lines = [f"pub const {name}: &[&str] = &["]
    for word in words:
        lines.append(f"    \"{word}\",")
    lines.append("];\n")
    return "\n".join(lines)


def main():
    adjectives = collect_words(ADJECTIVE_SOURCES)
    colors = collect_words(COLOR_SOURCES)
    adjectives |= colors

    food_words = collect_words(FOOD_SOURCES)

    scifi_words = collect_words(SCIFI_SOURCES)
    scifi_words |= collect_launch_vehicles()

    adj_list = sorted(adjectives)
    food_list = sorted(food_words)
    scifi_list = sorted(scifi_words)

    output = "// @generated by scripts/build_word_lists.py\n" + \
        write_array("ADJECTIVES", adj_list) + "\n" + \
        write_array("FOOD_NOUNS", food_list) + "\n" + \
        write_array("SCIFI_NOUNS", scifi_list)

    OUTPUT.write_text(output)
    print(f"Adjectives: {len(adj_list)}")
    print(f"Food nouns: {len(food_list)}")
    print(f"Sci-fi nouns: {len(scifi_list)}")

if __name__ == "__main__":
    main()
